### PR TITLE
fix the compiling issue

### LINKED ISSUE #5: Can't build. Trying to find nodesass.js within my source folder?
Tried installing with  iojs 3 / npm 2, and node 4 / npm 3. If I try to import a .scss file within my donejs project, this happens when trying to build.

```
Error loading "test@0.0.0#styles.scss!steal-sass@1.0.1#main" from "test@0.0.0#index.stache!done-autorender@0.6.0-pre.0#autorender" at file:/home/nmartel/repos/dev/test/src/index.stache
Error loading "nodesass" at file:/home/nmartel/repos/dev/test/nodesass.js
Error loading "nodesass" from "steal-sass@1.0.1#main" at file:/home/nmartel/repos/dev/test/node_modules/steal-sass/main.js
ENOENT: no such file or directory, open '/home/nmartel/repos/dev/test/nodesass.js'
    at Error (native
```

Is there something to configure with steal-tools?

### PR DESCRIPTION
**Pull request by pYr0x**
fix #5 

set the fully qualified path to the sass.js module.
if we make a build, we a currently not at the `sass-steal` working directory.
so node doesn't find the module. node will look at the root
for example:
`/node_module/sass.js`
but node should look into
`/node_modules/steal-sass/`

@matthewp look at the PR and give me some feedback

### CODE REVIEW

File: nodesass.js [hunk 1]
```diff
@@ -1,2 +1,4 @@
 var loader = require("@loader");
-module.exports = loader._nodeRequire("sass.js");
+// if we build your app with steal-tools, we are currently not in the steal-sass directory
+// we have to set the fully qualified path to the module
+module.exports = loader._nodeRequire(__dirname + "/node_modules/sass.js/dist/sass.sync.js");
```
Comment (matthewp) [inline nodesass.js]: Yeah, I think `nodeRequire` is always going to be the user's require. However this change will only work with npm2, with npm3 sass.js could be somewhere else. We should use nodeRequire.resolve first, something like:

``` js
var sassLocation = __dirname + "/node_modules/sass.js/dist/sass.sync.js";
try {
  sassLocation = loader._nodeRequire.resolve('sass.js/dist/sass.sync.js');
catch {}

module.exports = loader._nodeRequire(sassLocation);
```

Comment (pYr0x) [inline nodesass.js]: all right.. added

**Comment by matthewp** [comment]
Cool, thanks.

**Comment by matthewp** [comment]
@pYr0x I added you as a collaborator so you can push to this repo now.
